apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: sample-app-prod
spec:
  components:
    - name: sample-app
      type: webservice
      properties:
        image: tykola/hello-spring:ac235b41ff
        port: 8080
      traits:
        - type: annotations
          properties:
            configmap.reloader.stakater.com/reload: "sample-app-properties"
        - type: storage
          properties:
            configMap:
              - name: sample-app-properties
                mountOnly: false
                mountPath: /dumps
                # Mount ConfigMap to Env
                mountToEnv:
                  envName: ENV_PREFIX
                  configMapKey: env.prefix
        - type: gateway-ingress-url-rewrite
          properties:
            domain: localhost
            http:
              "/prod": 8080
            rewritePath: /