apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- name: sample-app-properties
  envs:
  - sample-app.properties

namespace: qa2

resources:
- https://raw.githubusercontent.com/lordpangan/kubevela-manifests/main/traits/gateway-ing-url-rewrite.yaml
- sample-app.yaml


generatorOptions:
  disableNameSuffixHash: true